# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://tuxpeople.github.io
baseurl: /www.thomas-deutsch.ch/
title: Thomas Deutsch
author: Thomas Deutsch
description: Mea fragmenti ab terra virtualis
avatar: profile.png
email: thomas@tuxpeople.org
#github: tuxpeople/www.thomas-deutsch.ch # username
twitter: tdeutsch
linkedin: thomas-deutsch-844a1839
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
